# ref. https://goreleaser.com/customization/build/
builds:
  - id: subnet-evm
    main: ./plugin
    binary: subnet-evm
    flags:
      - -v
    ldflags: -X github.com/ava-labs/subnet-evm/plugin/evm.Version=v{{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O -D__BLST_PORTABLE__ # Set the CGO flags to use the portable version of BLST
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CC=o64-clang
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: ava-labs
    name: subnet-evm
