// Code generated
// This file is a generated precompile contract test with the skeleton of test functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package bibliophile

import (
	"testing"

	"github.com/ava-labs/subnet-evm/core/state"
	"github.com/ava-labs/subnet-evm/precompile/testutils"
	"github.com/ava-labs/subnet-evm/vmerrs"
	"github.com/ethereum/go-ethereum/common"
	"github.com/stretchr/testify/require"
)

// TestRun tests the Run function of the precompile contract.
// These tests are run against the precompile contract directly with
// the given input and expected output. They're just a guide to
// help you write your own tests. These tests are for general cases like
// allowlist, readOnly behaviour, and gas cost. You should write your own
// tests for specific cases.
func TestRun(t *testing.T) {
	trader := common.HexToAddress("0x6900000000000000000000000000000000000069")
	tests := map[string]testutils.PrecompileTest{
		"insufficient gas for getNotionalPositionAndMargin should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				testInput := GetNotionalPositionAndMarginInput{
					Trader: trader,
				}
				input, err := PackGetNotionalPositionAndMargin(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: GetNotionalPositionAndMarginGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
		"insufficient gas for getPositionSizes should fail": {
			Caller: common.Address{1},
			InputFn: func(t testing.TB) []byte {
				testInput := common.HexToAddress("0x0300000000000000000000000000000000000000")
				input, err := PackGetPositionSizes(testInput)
				require.NoError(t, err)
				return input
			},
			SuppliedGas: GetPositionSizesGasCost - 1,
			ReadOnly:    false,
			ExpectedErr: vmerrs.ErrOutOfGas.Error(),
		},
	}
	// Run tests.
	for name, test := range tests {
		t.Run(name, func(t *testing.T) {
			test.Run(t, Module, state.NewTestStateDB(t))
		})
	}
}
