// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package hubbleconfigmanager

import (
	"errors"
	"fmt"
	"math/big"

	"github.com/ava-labs/subnet-evm/accounts/abi"
	"github.com/ava-labs/subnet-evm/precompile/allowlist"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
)

const (
	// Gas costs for each function. These are set to 0 by default.
	// You should set a gas cost for each function in your contract.
	// Generally, you should not set gas costs very low as this may cause your network to be vulnerable to DoS attacks.
	// There are some predefined gas costs in contract/utils.go that you can use.
	// This contract also uses AllowList precompile.
	// You should also increase gas costs of functions that read from AllowList storage.
	GetMaintenanceMarginGasCost    uint64 = contract.ReadGasCostPerSlot + allowlist.ReadAllowListGasCost // read 1 slot + read allow list
	GetMaxLiquidationRatioGasCost  uint64 = contract.ReadGasCostPerSlot + allowlist.ReadAllowListGasCost // read 1 slot + read allow list
	GetMinAllowableMarginGasCost   uint64 = contract.ReadGasCostPerSlot + allowlist.ReadAllowListGasCost // read 1 slot + read allow list
	GetMinSizeRequirementGasCost   uint64 = contract.ReadGasCostPerSlot + allowlist.ReadAllowListGasCost // read 1 slot + read allow list
	GetSpreadRatioThresholdGasCost uint64 = contract.ReadGasCostPerSlot + allowlist.ReadAllowListGasCost // read 1 slot + read allow list
	SetMaintenanceMarginGasCost    uint64 = contract.WriteGasCostPerSlot + allowlist.ReadAllowListGasCost // write 1 slot + read allow list
	SetMaxLiquidationRatioGasCost  uint64 = contract.WriteGasCostPerSlot + allowlist.ReadAllowListGasCost // write 1 slot + read allow list
	SetMinAllowableMarginGasCost   uint64 = contract.WriteGasCostPerSlot + allowlist.ReadAllowListGasCost // write 1 slot + read allow list
	SetMinSizeRequirementGasCost   uint64 = contract.WriteGasCostPerSlot + allowlist.ReadAllowListGasCost // write 1 slot + read allow list
	SetSpreadRatioThresholdGasCost uint64 = contract.WriteGasCostPerSlot + allowlist.ReadAllowListGasCost // write 1 slot + read allow list
)

// CUSTOM CODE STARTS HERE
// Reference imports to suppress errors from unused imports. This code and any unnecessary imports can be removed.
var (
	_ = abi.JSON
	_ = errors.New
	_ = big.NewInt
)

// Singleton StatefulPrecompiledContract and signatures.
var (
	ErrCannotSetMaintenanceMargin = errors.New("non-enabled cannot call setMaintenanceMargin")

	ErrCannotSetMaxLiquidationRatio = errors.New("non-enabled cannot call setMaxLiquidationRatio")

	ErrCannotSetMinAllowableMargin = errors.New("non-enabled cannot call setMinAllowableMargin")

	ErrCannotSetMinSizeRequirement = errors.New("non-enabled cannot call setMinSizeRequirement")

	ErrCannotSetSpreadRatioThreshold = errors.New("non-enabled cannot call setSpreadRatioThreshold")

	// HubbleConfigManagerRawABI contains the raw ABI of HubbleConfigManager contract.
	//go:embed contract.abi
	HubbleConfigManagerRawABI string

	HubbleConfigManagerABI = contract.ParseABI(HubbleConfigManagerRawABI)

	HubbleConfigManagerPrecompile = createHubbleConfigManagerPrecompile()
	spreadRatioThresholdKey       = common.Hash{'s', 'r', 't'}
	maintenanceMarginKey          = common.Hash{'m', 'm'}
	minAllowableMarginKey         = common.Hash{'m', 'a', 'm'}
	maxLiquidationRatioKey        = common.Hash{'m', 'l', 'r'}
	minSizeRequirementKey         = common.Hash{'m', 's', 'r'}
)

// GetHubbleConfigManagerAllowListStatus returns the role of [address] for the HubbleConfigManager list.
func GetHubbleConfigManagerAllowListStatus(stateDB contract.StateDB, address common.Address) allowlist.Role {
	return allowlist.GetAllowListStatus(stateDB, ContractAddress, address)
}

// SetHubbleConfigManagerAllowListStatus sets the permissions of [address] to [role] for the
// HubbleConfigManager list. Assumes [role] has already been verified as valid.
// This stores the [role] in the contract storage with address [ContractAddress]
// and [address] hash. It means that any reusage of the [address] key for different value
// conflicts with the same slot [role] is stored.
// Precompile implementations must use a different key than [address] for their storage.
func SetHubbleConfigManagerAllowListStatus(stateDB contract.StateDB, address common.Address, role allowlist.Role) {
	allowlist.SetAllowListRole(stateDB, ContractAddress, address, role)
}

// PackGetMaintenanceMargin packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetMaintenanceMargin() ([]byte, error) {
	return HubbleConfigManagerABI.Pack("getMaintenanceMargin")
}

// PackGetMaintenanceMarginOutput attempts to pack given maintenanceMargin of type *big.Int
// to conform the ABI outputs.
func PackGetMaintenanceMarginOutput(maintenanceMargin *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.PackOutput("getMaintenanceMargin", maintenanceMargin)
}

func getMaintenanceMargin(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetMaintenanceMarginGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE
	output := getMaintenanceMarginFromStateDB(accessibleState.GetStateDB())
	packedOutput, err := PackGetMaintenanceMarginOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// PackGetMaxLiquidationRatio packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetMaxLiquidationRatio() ([]byte, error) {
	return HubbleConfigManagerABI.Pack("getMaxLiquidationRatio")
}

// PackGetMaxLiquidationRatioOutput attempts to pack given maxLiquidationRatio of type *big.Int
// to conform the ABI outputs.
func PackGetMaxLiquidationRatioOutput(maxLiquidationRatio *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.PackOutput("getMaxLiquidationRatio", maxLiquidationRatio)
}

func getMaxLiquidationRatio(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetMaxLiquidationRatioGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	output := getMaxLiquidationRatioFromStateDB(accessibleState.GetStateDB())
	packedOutput, err := PackGetMaxLiquidationRatioOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// PackGetMinAllowableMargin packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetMinAllowableMargin() ([]byte, error) {
	return HubbleConfigManagerABI.Pack("getMinAllowableMargin")
}

// PackGetMinAllowableMarginOutput attempts to pack given minAllowableMargin of type *big.Int
// to conform the ABI outputs.
func PackGetMinAllowableMarginOutput(minAllowableMargin *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.PackOutput("getMinAllowableMargin", minAllowableMargin)
}

func getMinAllowableMargin(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetMinAllowableMarginGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE
	output := getMinAllowableMarginFromStateDB(accessibleState.GetStateDB())
	packedOutput, err := PackGetMinAllowableMarginOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// PackGetMinSizeRequirement packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetMinSizeRequirement() ([]byte, error) {
	return HubbleConfigManagerABI.Pack("getMinSizeRequirement")
}

// PackGetMinSizeRequirementOutput attempts to pack given minSizeRequirement of type *big.Int
// to conform the ABI outputs.
func PackGetMinSizeRequirementOutput(minSizeRequirement *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.PackOutput("getMinSizeRequirement", minSizeRequirement)
}

func getMinSizeRequirement(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetMinSizeRequirementGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE
	output := getMinSizeRequirementFromStateDB(accessibleState.GetStateDB())
	packedOutput, err := PackGetMinSizeRequirementOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// PackGetSpreadRatioThreshold packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetSpreadRatioThreshold() ([]byte, error) {
	return HubbleConfigManagerABI.Pack("getSpreadRatioThreshold")
}

// PackGetSpreadRatioThresholdOutput attempts to pack given spreadRatioThreshold of type *big.Int
// to conform the ABI outputs.
func PackGetSpreadRatioThresholdOutput(spreadRatioThreshold *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.PackOutput("getSpreadRatioThreshold", spreadRatioThreshold)
}

func getSpreadRatioThreshold(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetSpreadRatioThresholdGasCost); err != nil {
		return nil, 0, err
	}
	// no input provided for this function

	// CUSTOM CODE STARTS HERE
	output := getSpreadRatioThresholdFromStateDB(accessibleState.GetStateDB())
	packedOutput, err := PackGetSpreadRatioThresholdOutput(output)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackSetMaintenanceMarginInput attempts to unpack [input] into the *big.Int type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackSetMaintenanceMarginInput(input []byte) (*big.Int, error) {
	res, err := HubbleConfigManagerABI.UnpackInput("setMaintenanceMargin", input)
	if err != nil {
		return big.NewInt(0), err
	}
	unpacked := *abi.ConvertType(res[0], new(*big.Int)).(**big.Int)
	return unpacked, nil
}

// PackSetMaintenanceMargin packs [maintenanceMargin] of type *big.Int into the appropriate arguments for setMaintenanceMargin.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackSetMaintenanceMargin(maintenanceMargin *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.Pack("setMaintenanceMargin", maintenanceMargin)
}

func setMaintenanceMargin(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, SetMaintenanceMarginGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the SetMaintenanceMarginInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackSetMaintenanceMarginInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// Allow list is enabled and SetMaintenanceMargin is a state-changer function.
	// This part of the code restricts the function to be called only by enabled/admin addresses in the allow list.
	// You can modify/delete this code if you don't want this function to be restricted by the allow list.
	stateDB := accessibleState.GetStateDB()
	// Verify that the caller is in the allow list and therefore has the right to call this function.
	callerStatus := allowlist.GetAllowListStatus(stateDB, ContractAddress, caller)
	if !callerStatus.IsEnabled() {
		return nil, remainingGas, fmt.Errorf("%w: %s", ErrCannotSetMaintenanceMargin, caller)
	}
	// allow list code ends here.

	// CUSTOM CODE STARTS HERE
	setMaintenanceMarginInStateDB(stateDB, inputStruct)
	// this function does not return an output, leave this one as is
	packedOutput := []byte{}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackSetMaxLiquidationRatioInput attempts to unpack [input] into the *big.Int type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackSetMaxLiquidationRatioInput(input []byte) (*big.Int, error) {
	res, err := HubbleConfigManagerABI.UnpackInput("setMaxLiquidationRatio", input)
	if err != nil {
		return big.NewInt(0), err
	}
	unpacked := *abi.ConvertType(res[0], new(*big.Int)).(**big.Int)
	return unpacked, nil
}

// PackSetMaxLiquidationRatio packs [maxLiquidationRatio] of type *big.Int into the appropriate arguments for setMaxLiquidationRatio.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackSetMaxLiquidationRatio(maxLiquidationRatio *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.Pack("setMaxLiquidationRatio", maxLiquidationRatio)
}

func setMaxLiquidationRatio(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, SetMaxLiquidationRatioGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the SetMaxLiquidationRatioInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackSetMaxLiquidationRatioInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// Allow list is enabled and SetMaxLiquidationRatio is a state-changer function.
	// This part of the code restricts the function to be called only by enabled/admin addresses in the allow list.
	// You can modify/delete this code if you don't want this function to be restricted by the allow list.
	stateDB := accessibleState.GetStateDB()
	// Verify that the caller is in the allow list and therefore has the right to call this function.
	callerStatus := allowlist.GetAllowListStatus(stateDB, ContractAddress, caller)
	if !callerStatus.IsEnabled() {
		return nil, remainingGas, fmt.Errorf("%w: %s", ErrCannotSetMaxLiquidationRatio, caller)
	}
	// allow list code ends here.

	// CUSTOM CODE STARTS HERE
	setMaxLiquidationRatioInStateDB(stateDB, inputStruct)
	// this function does not return an output, leave this one as is
	packedOutput := []byte{}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackSetMinAllowableMarginInput attempts to unpack [input] into the *big.Int type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackSetMinAllowableMarginInput(input []byte) (*big.Int, error) {
	res, err := HubbleConfigManagerABI.UnpackInput("setMinAllowableMargin", input)
	if err != nil {
		return big.NewInt(0), err
	}
	unpacked := *abi.ConvertType(res[0], new(*big.Int)).(**big.Int)
	return unpacked, nil
}

// PackSetMinAllowableMargin packs [minAllowableMargin] of type *big.Int into the appropriate arguments for setMinAllowableMargin.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackSetMinAllowableMargin(minAllowableMargin *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.Pack("setMinAllowableMargin", minAllowableMargin)
}

func setMinAllowableMargin(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, SetMinAllowableMarginGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the SetMinAllowableMarginInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackSetMinAllowableMarginInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// Allow list is enabled and SetMinAllowableMargin is a state-changer function.
	// This part of the code restricts the function to be called only by enabled/admin addresses in the allow list.
	// You can modify/delete this code if you don't want this function to be restricted by the allow list.
	stateDB := accessibleState.GetStateDB()
	// Verify that the caller is in the allow list and therefore has the right to call this function.
	callerStatus := allowlist.GetAllowListStatus(stateDB, ContractAddress, caller)
	if !callerStatus.IsEnabled() {
		return nil, remainingGas, fmt.Errorf("%w: %s", ErrCannotSetMinAllowableMargin, caller)
	}
	// allow list code ends here.

	// CUSTOM CODE STARTS HERE
	setMinAllowableMarginInStateDB(stateDB, inputStruct)
	// this function does not return an output, leave this one as is
	packedOutput := []byte{}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackSetMinSizeRequirementInput attempts to unpack [input] into the *big.Int type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackSetMinSizeRequirementInput(input []byte) (*big.Int, error) {
	res, err := HubbleConfigManagerABI.UnpackInput("setMinSizeRequirement", input)
	if err != nil {
		return big.NewInt(0), err
	}
	unpacked := *abi.ConvertType(res[0], new(*big.Int)).(**big.Int)
	return unpacked, nil
}

// PackSetMinSizeRequirement packs [minSizeRequirement] of type *big.Int into the appropriate arguments for setMinSizeRequirement.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackSetMinSizeRequirement(minSizeRequirement *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.Pack("setMinSizeRequirement", minSizeRequirement)
}

func setMinSizeRequirement(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, SetMinSizeRequirementGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the SetMinSizeRequirementInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackSetMinSizeRequirementInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// Allow list is enabled and SetMinSizeRequirement is a state-changer function.
	// This part of the code restricts the function to be called only by enabled/admin addresses in the allow list.
	// You can modify/delete this code if you don't want this function to be restricted by the allow list.
	stateDB := accessibleState.GetStateDB()
	// Verify that the caller is in the allow list and therefore has the right to call this function.
	callerStatus := allowlist.GetAllowListStatus(stateDB, ContractAddress, caller)
	if !callerStatus.IsEnabled() {
		return nil, remainingGas, fmt.Errorf("%w: %s", ErrCannotSetMinSizeRequirement, caller)
	}
	// allow list code ends here.

	// CUSTOM CODE STARTS HERE
	setMinSizeRequirementInStateDB(stateDB, inputStruct)
	// this function does not return an output, leave this one as is
	packedOutput := []byte{}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackSetSpreadRatioThresholdInput attempts to unpack [input] into the *big.Int type argument
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackSetSpreadRatioThresholdInput(input []byte) (*big.Int, error) {
	res, err := HubbleConfigManagerABI.UnpackInput("setSpreadRatioThreshold", input)
	if err != nil {
		return big.NewInt(0), err
	}
	unpacked := *abi.ConvertType(res[0], new(*big.Int)).(**big.Int)
	return unpacked, nil
}

// PackSetSpreadRatioThreshold packs [spreadRatioThreshold] of type *big.Int into the appropriate arguments for setSpreadRatioThreshold.
// the packed bytes include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackSetSpreadRatioThreshold(spreadRatioThreshold *big.Int) ([]byte, error) {
	return HubbleConfigManagerABI.Pack("setSpreadRatioThreshold", spreadRatioThreshold)
}

func setSpreadRatioThreshold(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, SetSpreadRatioThresholdGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// attempts to unpack [input] into the arguments to the SetSpreadRatioThresholdInput.
	// Assumes that [input] does not include selector
	// You can use unpacked [inputStruct] variable in your code
	inputStruct, err := UnpackSetSpreadRatioThresholdInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	// Allow list is enabled and SetSpreadRatioThreshold is a state-changer function.
	// This part of the code restricts the function to be called only by enabled/admin addresses in the allow list.
	// You can modify/delete this code if you don't want this function to be restricted by the allow list.
	stateDB := accessibleState.GetStateDB()
	// Verify that the caller is in the allow list and therefore has the right to call this function.
	callerStatus := allowlist.GetAllowListStatus(stateDB, ContractAddress, caller)
	if !callerStatus.IsEnabled() {
		return nil, remainingGas, fmt.Errorf("%w: %s", ErrCannotSetSpreadRatioThreshold, caller)
	}
	// allow list code ends here.

	// CUSTOM CODE STARTS HERE
	setSpreadRatioThresholdInStateDB(stateDB, inputStruct)
	// this function does not return an output, leave this one as is
	packedOutput := []byte{}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// createHubbleConfigManagerPrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.
// Access to the getters/setters is controlled by an allow list for ContractAddress.
func createHubbleConfigManagerPrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction
	functions = append(functions, allowlist.CreateAllowListFunctions(ContractAddress)...)

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"getMaintenanceMargin":    getMaintenanceMargin,
		"getMaxLiquidationRatio":  getMaxLiquidationRatio,
		"getMinAllowableMargin":   getMinAllowableMargin,
		"getMinSizeRequirement":   getMinSizeRequirement,
		"getSpreadRatioThreshold": getSpreadRatioThreshold,
		"setMaintenanceMargin":    setMaintenanceMargin,
		"setMaxLiquidationRatio":  setMaxLiquidationRatio,
		"setMinAllowableMargin":   setMinAllowableMargin,
		"setMinSizeRequirement":   setMinSizeRequirement,
		"setSpreadRatioThreshold": setSpreadRatioThreshold,
	}

	for name, function := range abiFunctionMap {
		method, ok := HubbleConfigManagerABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}

func GetSpreadRatioThreshold(stateDB contract.StateDB) *big.Int {
	return getSpreadRatioThresholdFromStateDB(stateDB)
}

func GetMaintenanceMargin(stateDB contract.StateDB) *big.Int {
	return getMaintenanceMarginFromStateDB(stateDB)
}

func GetMinAllowableMargin(stateDb contract.StateDB) *big.Int {
	return getMinAllowableMarginFromStateDB(stateDb)
}

func GetMaxLiquidationRatio(stateDB contract.StateDB) *big.Int {
	return getMaxLiquidationRatioFromStateDB(stateDB)
}

func GetMinSizeRequirement(stateDB contract.StateDB) *big.Int {
	return getMinSizeRequirementFromStateDB(stateDB)
}

func getSpreadRatioThresholdFromStateDB(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, spreadRatioThresholdKey)
	return new(big.Int).SetBytes(value[:])
}

func setSpreadRatioThresholdInStateDB(stateDB contract.StateDB, value *big.Int) {
	stateDB.SetState(ContractAddress, spreadRatioThresholdKey, common.BigToHash(value))
}

func getMaintenanceMarginFromStateDB(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, maintenanceMarginKey)
	return new(big.Int).SetBytes(value[:])
}

func setMaintenanceMarginInStateDB(stateDB contract.StateDB, value *big.Int) {
	stateDB.SetState(ContractAddress, maintenanceMarginKey, common.BigToHash(value))
}

func getMaxLiquidationRatioFromStateDB(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, maxLiquidationRatioKey)
	return new(big.Int).SetBytes(value[:])
}

func setMaxLiquidationRatioInStateDB(stateDB contract.StateDB, value *big.Int) {
	stateDB.SetState(ContractAddress, maxLiquidationRatioKey, common.BigToHash(value))
}

func getMinAllowableMarginFromStateDB(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, minAllowableMarginKey)
	return new(big.Int).SetBytes(value[:])
}

func setMinAllowableMarginInStateDB(stateDB contract.StateDB, value *big.Int) {
	stateDB.SetState(ContractAddress, minAllowableMarginKey, common.BigToHash(value))
}

func getMinSizeRequirementFromStateDB(stateDB contract.StateDB) *big.Int {
	value := stateDB.GetState(ContractAddress, minSizeRequirementKey)
	return new(big.Int).SetBytes(value[:])
}

func setMinSizeRequirementInStateDB(stateDB contract.StateDB, value *big.Int) {
	stateDB.SetState(ContractAddress, minSizeRequirementKey, common.BigToHash(value))
}
