// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package hubbleconfigmanager

import (
	"fmt"
	"math/big"

	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/precompile/modules"
	"github.com/ava-labs/subnet-evm/precompile/precompileconfig"

	"github.com/ethereum/go-ethereum/common"
)

var _ contract.Configurator = &configurator{}

// ConfigKey is the key used in json config files to specify this precompile precompileconfig.
// must be unique across all precompiles.
const ConfigKey = "hubbleConfigManagerConfig"

// ContractAddress is the defined address of the precompile contract.
// This should be unique across all precompile contracts.
// See precompile/registry/registry.go for registered precompile contracts and more information.
var ContractAddress = common.HexToAddress("0x0300000000000000000000000000000000000000") // SET A SUITABLE HEX ADDRESS HERE

// Module is the precompile module. It is used to register the precompile contract.
var Module = modules.Module{
	ConfigKey:    ConfigKey,
	Address:      ContractAddress,
	Contract:     HubbleConfigManagerPrecompile,
	Configurator: &configurator{},
}

var (
	DefaultSpreadRatioThreshold = big.NewInt(1e6)
	DefaultMinAllowableMargin   = big.NewInt(2 * 1e5) // 5x
	DefaultMaintenanceMargin    = big.NewInt(1e5)
	DefaultMaxLiquidationRatio  = big.NewInt(25 * 1e4) // 25%
	DefaultMinSizeRequirement   = big.NewInt(1e16)
)

type configurator struct{}

func init() {
	// Register the precompile module.
	// Each precompile contract registers itself through [RegisterModule] function.
	if err := modules.RegisterModule(Module); err != nil {
		panic(err)
	}
}

// MakeConfig returns a new precompile config instance.
// This is required for Marshal/Unmarshal the precompile config.
func (*configurator) MakeConfig() precompileconfig.Config {
	return new(Config)
}

// Configure configures [state] with the given [cfg] precompileconfig.
// This function is called by the EVM once per precompile contract activation.
// You can use this function to set up your precompile contract's initial state,
// by using the [cfg] config and [state] stateDB.
func (*configurator) Configure(chainConfig contract.ChainConfig, cfg precompileconfig.Config, state contract.StateDB, _ contract.BlockContext) error {
	config, ok := cfg.(*Config)
	if !ok {
		return fmt.Errorf("incorrect config %T: %v", config, config)
	}
	// CUSTOM CODE STARTS HERE
	setSpreadRatioThresholdInStateDB(state, DefaultSpreadRatioThreshold)
	setMaintenanceMarginInStateDB(state, DefaultMaintenanceMargin)
	setMaxLiquidationRatioInStateDB(state, DefaultMaxLiquidationRatio)
	setMinSizeRequirementInStateDB(state, DefaultMinSizeRequirement)
	setMinAllowableMarginInStateDB(state, DefaultMinAllowableMargin)
	// AllowList is activated for this precompile. Configuring allowlist addresses here.
	return config.AllowListConfig.Configure(state, ContractAddress)
}
