// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package warp

import (
	"fmt"

	"github.com/ava-labs/avalanchego/ids"
	"github.com/ava-labs/avalanchego/vms/platformvm/warp"
	"github.com/ava-labs/subnet-evm/precompile/contract"
	"github.com/ava-labs/subnet-evm/vmerrs"
	warpMessages "github.com/ava-labs/subnet-evm/warp/messages"

	_ "embed"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/common/math"
	"github.com/ethereum/go-ethereum/log"
)

const (
	GetBlockchainIDGasCost        uint64 = 2 // Based on GasQuickStep used in existing EVM instructions
	SendWarpMessageGasCost        uint64 = 0 // TODO base this off of the cost of performing this in the EVM + cost of signing a message
	GetVerifiedWarpMessageGasCost uint64 = 0 // TODO: base this off of the number of signers
	GasCostPerWarpSigner          uint64 = 0 // TODO
	GasCostPerWarpMessageBytes    uint64 = 0 // TODO
)

// Singleton StatefulPrecompiledContract and signatures.
var (

	// WarpRawABI contains the raw ABI of Warp contract.
	//go:embed contract.abi
	WarpRawABI string

	WarpABI = contract.ParseABI(WarpRawABI)

	WarpPrecompile = createWarpPrecompile()
)

// WarpMessage is an auto generated low-level Go binding around an user-defined struct.
type WarpMessage struct {
	OriginChainID       [32]byte
	OriginSenderAddress [32]byte
	DestinationChainID  [32]byte
	DestinationAddress  [32]byte
	Payload             []byte
}

type GetVerifiedWarpMessageOutput struct {
	Message WarpMessage
	Exists  bool
}

type SendWarpMessageInput struct {
	DestinationChainID [32]byte
	DestinationAddress [32]byte
	Payload            []byte
}

// PackGetBlockchainID packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetBlockchainID() ([]byte, error) {
	return WarpABI.Pack("getBlockchainID")
}

// PackGetBlockchainIDOutput attempts to pack given blockchainID of type [32]byte
// to conform the ABI outputs.
func PackGetBlockchainIDOutput(blockchainID [32]byte) ([]byte, error) {
	return WarpABI.PackOutput("getBlockchainID", blockchainID)
}

func getBlockchainID(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetBlockchainIDGasCost); err != nil {
		return nil, 0, err
	}
	packedOutput, err := PackGetBlockchainIDOutput(accessibleState.GetSnowContext().ChainID)
	if err != nil {
		return nil, remainingGas, err
	}

	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// PackGetVerifiedWarpMessage packs the include selector (first 4 func signature bytes).
// This function is mostly used for tests.
func PackGetVerifiedWarpMessage() ([]byte, error) {
	return WarpABI.Pack("getVerifiedWarpMessage")
}

// PackGetVerifiedWarpMessageOutput attempts to pack given [outputStruct] of type GetVerifiedWarpMessageOutput
// to conform the ABI outputs.
func PackGetVerifiedWarpMessageOutput(outputStruct GetVerifiedWarpMessageOutput) ([]byte, error) {
	return WarpABI.PackOutput("getVerifiedWarpMessage",
		outputStruct.Message,
		outputStruct.Exists,
	)
}

func getVerifiedWarpMessage(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, _ []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, GetVerifiedWarpMessageGasCost); err != nil {
		return nil, 0, err
	}
	// Ignore input since there are no arguments

	predicateBytes, exists := accessibleState.GetStateDB().GetPredicateStorageSlots(ContractAddress)
	// If there is no such value, return false to the caller.
	// Note: decoding errors will return an error instead.
	if !exists {
		packedOutput, err := PackGetVerifiedWarpMessageOutput(GetVerifiedWarpMessageOutput{
			Exists: false,
		})
		if err != nil {
			return nil, remainingGas, err
		}
		return packedOutput, remainingGas, nil
	}

	msgBytesGas, overflow := math.SafeMul(GasCostPerWarpMessageBytes, uint64(len(predicateBytes)))
	if overflow {
		return nil, remainingGas, fmt.Errorf("overflow calculating gas cost for warp message bytes of size %d", len(predicateBytes))
	}
	if remainingGas, err = contract.DeductGas(remainingGas, msgBytesGas); err != nil {
		return nil, 0, err
	}

	warpMessage, err := warp.ParseMessage(predicateBytes)
	if err != nil {
		return nil, remainingGas, err
	}

	addressedPayload, err := warpMessages.ParseAddressedPayload(warpMessage.UnsignedMessage.Payload)
	if err != nil {
		return nil, remainingGas, err
	}
	packedOutput, err := PackGetVerifiedWarpMessageOutput(GetVerifiedWarpMessageOutput{
		Message: WarpMessage{
			OriginChainID:       warpMessage.SourceChainID,
			OriginSenderAddress: addressedPayload.SourceAddress,
			DestinationChainID:  warpMessage.DestinationChainID,
			DestinationAddress:  addressedPayload.DestinationAddress,
			Payload:             addressedPayload.Payload,
		},
		Exists: true,
	})
	if err != nil {
		return nil, remainingGas, err
	}

	// TODO: remove
	log.Info("getVerifiedWarpMessage successful", "originaChainID", warpMessage.SourceChainID, "originSenderAddress", addressedPayload.SourceAddress, "destinationChainID", warpMessage.DestinationChainID, "destinationAddress", addressedPayload.DestinationAddress, "payload", common.Bytes2Hex(addressedPayload.Payload))
	// Return the packed output and the remaining gas
	return packedOutput, remainingGas, nil
}

// UnpackSendWarpMessageInput attempts to unpack [input] as SendWarpMessageInput
// assumes that [input] does not include selector (omits first 4 func signature bytes)
func UnpackSendWarpMessageInput(input []byte) (SendWarpMessageInput, error) {
	inputStruct := SendWarpMessageInput{}
	err := WarpABI.UnpackInputIntoInterface(&inputStruct, "sendWarpMessage", input)

	return inputStruct, err
}

// PackSendWarpMessage packs [inputStruct] of type SendWarpMessageInput into the appropriate arguments for sendWarpMessage.
func PackSendWarpMessage(inputStruct SendWarpMessageInput) ([]byte, error) {
	return WarpABI.Pack("sendWarpMessage", inputStruct.DestinationChainID, inputStruct.DestinationAddress, inputStruct.Payload)
}

func sendWarpMessage(accessibleState contract.AccessibleState, caller common.Address, addr common.Address, input []byte, suppliedGas uint64, readOnly bool) (ret []byte, remainingGas uint64, err error) {
	if remainingGas, err = contract.DeductGas(suppliedGas, SendWarpMessageGasCost); err != nil {
		return nil, 0, err
	}
	if readOnly {
		return nil, remainingGas, vmerrs.ErrWriteProtection
	}
	// unpack the arguemnts
	inputStruct, err := UnpackSendWarpMessageInput(input)
	if err != nil {
		return nil, remainingGas, err
	}

	var (
		sourceChainID      = accessibleState.GetSnowContext().ChainID
		destinationChainID = inputStruct.DestinationChainID
		sourceAddress      = caller.Hash()
		destinationAddress = inputStruct.DestinationAddress
		payload            = inputStruct.Payload
	)

	addressedPayload, err := warp.NewAddressedPayload(
		ids.ID(sourceAddress),
		destinationAddress,
		payload,
	)
	if err != nil {
		return nil, remainingGas, err
	}
	warpMessage, err := warp.NewUnsignedMessage(
		sourceChainID,
		destinationChainID,
		addressedPayload.Bytes(),
	)
	if err != nil {
		return nil, remainingGas, err
	}

	// Add a log to be handled if this action is finalized.
	accessibleState.GetStateDB().AddLog(
		ContractAddress,
		[]common.Hash{
			WarpABI.Events["SendWarpMessage"].ID,
			destinationChainID,
			destinationAddress,
			sourceAddress,
		},
		warpMessage.Bytes(),
		accessibleState.GetBlockContext().Number().Uint64(),
	)

	// Return an empty output and the remaining gas
	return []byte{}, remainingGas, nil
}

// createWarpPrecompile returns a StatefulPrecompiledContract with getters and setters for the precompile.
func createWarpPrecompile() contract.StatefulPrecompiledContract {
	var functions []*contract.StatefulPrecompileFunction

	abiFunctionMap := map[string]contract.RunStatefulPrecompileFunc{
		"getBlockchainID":        getBlockchainID,
		"getVerifiedWarpMessage": getVerifiedWarpMessage,
		"sendWarpMessage":        sendWarpMessage,
	}

	for name, function := range abiFunctionMap {
		method, ok := WarpABI.Methods[name]
		if !ok {
			panic(fmt.Errorf("given method (%s) does not exist in the ABI", name))
		}
		functions = append(functions, contract.NewStatefulPrecompileFunction(method.ID, function))
	}
	// Construct the contract with no fallback function.
	statefulContract, err := contract.NewStatefulPrecompileContract(nil, functions)
	if err != nil {
		panic(err)
	}
	return statefulContract
}
