name: Bench

on:
  workflow_dispatch:
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - run: go mod download
        shell: bash
      - run: ./scripts/build_bench_precompiles.sh
        shell: bash
    
