name: Bench

on:
  workflow_dispatch:
  pull_request:

jobs:
  bench:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '~1.20.12'
          check-latest: true
      - run: go mod download
        shell: bash
      - run: ./scripts/build_bench_precompiles.sh
        shell: bash
