name: JSON Network Config Check

on:
  push:
    paths:
      - 'networks/**/**.json'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1.0.3
        with:
          pattern: "\\.json$"
