name: Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      vm_id:
        description: "The ID of the VM (binary dst in Docker image)"
        default: ""
        required: false
        type: string

  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Create multiplatform docker builder
        run: docker buildx create --use
      - name: Build and publish images to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_REPO: "avaplatform/subnet-evm"
          PUBLISH: 1
          PLATFORMS: "linux/amd64,linux/arm64"
        run: scripts/build_docker_image.sh ${{ inputs.vm_id }}
