name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  publish_docker_image:
    name: Publish Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ secrets.docker_pass }} | docker login --username ${{ secrets.docker_username }} --password-stdin
        shell: bash
      - run: CURRENT_BRANCH=${{ github.head_ref || github.ref_name }} PUSH_DOCKER_IMAGE=true ./scripts/build_image.sh
        shell: bash
