name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - master

  workflow_call:
    inputs:
      vm_id:
        description: 'The ID of the VM (binary dst in Docker image)'
        default: 'meq3bv7qCMZZ69L8xZRLwyKnWp6chRwyscq8VPtHWignRQVVF'
        required: false
        type: string

jobs:
  publish_docker_image:
    name: Publish Docker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Publish image to Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          DOCKER_REPO: "avaplatform/subnet-evm"
        run: .github/workflows/publish_docker_image.sh ${{ inputs.vm_id }}
