name: Trigger Antithesis

on:
  schedule:
    # When adjusting the schedule and duration of execution, make sure
    # to check the schedule of antithesis jobs scheduled by other
    # repos (avalanchego and hypersdk). Ideally the schedules for
    # different test setups should not overlap to avoid unintended
    # resource contention.
    - cron: '0 14 * * *' # Every day at 2PM UTC
  workflow_dispatch:
    inputs:
      duration:
        description: 'The duration (in hours) to run the test for'
        default: '0.5'
        required: true
        type: string
      recipients:
        description: 'Comma-seperated email addresses to send the test report to'
        required: true
        type: string
      image_tag:
        description: 'The image tag to target'
        default: latest
        required: true
        type: string

jobs:
  antithesis:
    name: Run Antithesis
    runs-on: ubuntu-latest
    steps:
      - uses: antithesishq/antithesis-trigger-action@v0.5
        with:
          notebook_name: avalanche
          tenant: avalanche
          username: ${{ secrets.ANTITHESIS_USERNAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.ANTITHESIS_GH_PAT }}
          config_image: antithesis-subnet-evm-config:${{ github.event.inputs.image_tag || 'latest' }}
          images: antithesis-subnet-evm-workload:${{ github.event.inputs.image_tag || 'latest' }};antithesis-subnet-evm-node:${{ github.event.inputs.image_tag || 'latest' }}
          email_recipients: ${{ github.event.inputs.recipients || secrets.ANTITHESIS_RECIPIENTS }}
          # Duration is in hours
          additional_parameters: |-
            custom.duration=${{ github.event.inputs.duration || '7.5' }}
            custom.workload=subnet-evm
